### ISSUE TITLE
wordlist.txt

### ISSUE THREAD

**Issue by ranjithprethan** [nidem/kerberoast#12]
Hi,
what does that wordlist file contain? does it contain the hashes of the commonly used passwords? can you please provide us the wordlist file?  or do we need to create our own?

./tgsrepcrack.py wordlist.txt

Thanks. Much appreciated.

**Comment by nidem** [comment]
I don't have a wordlist. It is any sort of wordlist. 

At this point, do NOT use this tool for cracking. John the Ripper and Hashcat both support cracking this format and they are significantly faster.
