### ISSUE TITLE
Should switch to Python 3

### ISSUE THREAD

**Issue by rhertzog** [nidem/kerberoast#14]
Python 2.x will no longer be supported by their upstream developers in 2020. Thus Debian developers are actively removing Python 2 support in Debian Testing with the goal of getting rid of Python 2 in Debian 11 (bullseye).

Since Kali Linux is based on Debian Testing, we have to follow along. And since kerberoast is part of Kali, we would like to have a version of kerberoast that works with Python 3.

All your dependencies are already available for Python 3 so there should be no real blockers.

Do you have plans to port kerberoast to Python 3 ?

Tracking bug in Kali: https://gitlab.com/kalilinux/packages/kerberoast/issues/1

**Comment by rhertzog** [comment]
@nidem Ping? Any plans to update it to Python3?

We (the Kali packagers) are trying to update it ourselves but as we're not real end users it's hard for us to test it. If you want to have a look at it as a starting point the patch is currently here:
https://gitlab.com/kalilinux/packages/kerberoast/-/blob/kali/master/debian/patches/Convert-to-Python-3.patch

**Comment by nidem** [comment]
I have some pieces converted. Let me look into this and covert the rest...

**Comment by nidem** [comment]
I believe it is working with python3 now

**Comment by nidem** [comment]
fixed in commit 41e4cfccf60d13bad28cc7be34277f88fb07dd3d
