### ISSUE TITLE
Rewrite error

### ISSUE THREAD

**Issue by kN6jq** [nidem/kerberoast#23]
when i try Rewrite
![image](https://user-images.githubusercontent.com/27048404/113707771-fa54d080-9712-11eb-8021-99f091b87ac7.png)
![image](https://user-images.githubusercontent.com/27048404/113707835-0d67a080-9713-11eb-9de2-f03ee4be77fe.png)

what happend?

**Comment by jorgejams88** [comment]
Confirmed, even with the example ticket, the same error occurs:

```
python3 -tt ./kerberoast.py -p phoenix1 -r ./examples/MSSQLSvc-sql01.medin.local.kirbi -w ./examples/sql.kirbi2 -u 500  

Traceback (most recent call last):
  File "/opt/repos/kerberoast/./kerberoast.py", line 225, in <module>
    pacobj = PAC.PAC(pac)
NameError: name 'PAC' is not defined

```

I was trying to troubleshoot the issue, I tried importing PAC differently
`from pac import PAC`

But the way it was used in kerberoast.py, created a different error:

```
python3 -tt ./kerberoast.py  -p phoenix1 -r ./examples/MSSQLSvc-sql01.medin.local.kirbi -w ./examples/sql.kirbi2 -u 500

Traceback (most recent call last):
  File "/opt/repos/kerberoast/./kerberoast.py", line 225, in <module>
    pacobj = PAC.PAC(pac)
AttributeError: type object 'PAC' has no attribute 'PAC'
```

Then I changed the code so it uses PAC and not PAC.PAC, but then this happened:

```
python3 -tt ./kerberoast.py -p phoenix1 -r ./examples/MSSQLSvc-sql01.medin.local.kirbi -w ./examples/sql.kirbi2 -u 500

Traceback (most recent call last):
  File "/opt/repos/kerberoast/./kerberoast.py", line 225, in <module>
    pacobj = PAC(pac)
  File "/opt/repos/kerberoast/pac.py", line 466, in __init__
    self.load(pac)
  File "/opt/repos/kerberoast/pac.py", line 477, in load
    numentries, self.Version = struct.unpack('<II', pac[:8])
TypeError: a bytes-like object is required, not 'str'
```
I have no idea what else to try.

**Comment by nse-bse** [comment]
Facing the same issue. Does anyone know how to solve it? @nidem Please?

**Comment by blitztide** [comment]
I've been having a look at it, there are a lot of issues where it has been ported to python3 and strings are treated as bytes and vice-versa.

**Comment by blitztide** [comment]
@nse-bse @Xm17 @jorgejams88 please can you check if this resolves your issues.

**Comment by allennic** [comment]
> @nse-bse @Xm17 @jorgejams88 please can you check if this resolves your issues.

I try 3.6,3.7,3.8,3.9 version.
Still the same, not fix this issues.
