### ISSUE TITLE
Feature Request: Verbose TGSrepCrack

### ISSUE THREAD

**Issue by mubix** [nidem/kerberoast#5]
It would be nice if tgsrepcrack would be a bit more verbose, let you know what kerberos tickets it's loaded, maybe even showing what the service is that it picks out of the ticket, that way it may show if any tickets are garbage

**Comment by nidem** [comment]
It isn't possible to know the service. It could look at the IP and port.

**Comment by nidem** [comment]
To clarify...
 - If a ticket is cracked I can get this value
 - If it is extracted from a mimikatz.kirbi file I can get this value

I can't get the name from a ticket caught on the wire. But truthfully, the JtR module is a lot faster and better.
